#!/bin/bash
currentDir=$(pwd)

mkdir -p ~/bin/
cd ~/bin/
if [ ! -e push_tools ];then
pwd
git clone git@192.168.8.201:alps/push_tools.git
fi

cd push_tools
git checkout -f  > /dev/null
git clean -fd    > /dev/null
git pull    > /dev/null 
##
cd $currentDir
##
chmod 775 ~/bin/push_tools/pushcode.py
python ~/bin/push_tools/pushcode.py




